server:
  port: 8080
spring:
  config:
    import: optional:file:/data/playground/connConfig.yml #敏感或按环境变化的配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath*:/mapper/*.xml